# Generated by Django 4.2 on 2024-12-17 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('title', models.CharField(max_length=255, verbose_name='تیتر')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('name', models.CharField(max_length=255, verbose_name='اسم')),
                ('cost', models.FloatField(validators=[menu.models.validate_positive], verbose_name='قیمت ( ریال ) ')),
                ('picture', models.ImageField(blank=True, default='menu_images/default_image.jpg', upload_to='menu_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('name', models.CharField(max_length=255, verbose_name='اسم')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('picture', models.ImageField(blank=True, default='media/restaurants/default_image.jpg', upload_to='restaurants/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL, verbose_name='صاحب رستوران')),
            ],
            options={
                'verbose_name': 'رستوران',
                'verbose_name_plural': 'رستوران ها',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('rate', models.IntegerField(validators=[menu.models.validate_rate], verbose_name='امتیاز')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.restaurant', verbose_name='رستوران')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.order', verbose_name='سفارش')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.restaurant', verbose_name='رستوران')),
            ],
            options={
                'verbose_name': 'سفارش رستوران',
                'verbose_name_plural': 'سفارشات رستوران ها',
            },
        ),
    ]
